steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: emojivoto-web Container Build
    args: [ 'build', '-t', 'asia-docker.pkg.dev/${PROJECT_ID}/asia.gcr.io/emojivoto-web:${SHORT_SHA}', 'emojivoto-web/' ]

  - name: 'gcr.io/cloud-builders/docker'
    id: emojivoto-web Container Push
    args: [ 'push', 'asia-docker.pkg.dev/${PROJECT_ID}/asia.gcr.io/emojivoto-web:${SHORT_SHA}' ]
    waitFor: ['emojivoto-web Container Build']

  - name: "gcr.io/cloud-builders/gke-deploy"
    id: emojivoto-web pod GKE deploy
    args:
      - run
      - --filename=deployment/web.yml
      - --image=asia-docker.pkg.dev/${PROJECT_ID}/asia.gcr.io/emojivoto-web:${SHORT_SHA}
      - --location=asia-south2-c
      - --cluster=sanjit-gke-demo
      - --output=weboutput
    waitFor: ['emojivoto-web Container Push']

  - name: 'gcr.io/cloud-builders/docker'
    id: emojivoto-emoji-svc Container Build
    args: [ 'build', '-t', 'asia-docker.pkg.dev/${PROJECT_ID}/asia.gcr.io/emojivoto-emoji-svc:${SHORT_SHA}', 'emojivoto-emoji-svc/' ]
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/docker'
    id: emojivoto-emoji-svc Container Push
    args: [ 'push', 'asia-docker.pkg.dev/${PROJECT_ID}/asia.gcr.io/emojivoto-emoji-svc:${SHORT_SHA}' ]
    waitFor: ['emojivoto-emoji-svc Container Build']

  - name: "gcr.io/cloud-builders/gke-deploy"
    id: emojivoto-emoji-svc pod GKE deploy
    args:
      - run
      - --filename=deployment/emoji.yml
      - --image=asia-docker.pkg.dev/${PROJECT_ID}/asia.gcr.io/emojivoto-emoji-svc:${SHORT_SHA}
      - --location=asia-south2-c
      - --cluster=sanjit-gke-demo
      - --output=emojioutput
    waitFor: ['emojivoto-emoji-svc Container Push']

  - name: 'gcr.io/cloud-builders/docker'
    id: emojivoto-voting-svc Container Build
    args: [ 'build', '-t', 'asia-docker.pkg.dev/${PROJECT_ID}/asia.gcr.io/emojivoto-voting-svc:${SHORT_SHA}', 'emojivoto-voting-svc/' ]
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/docker'
    id: emojivoto-voting-svc Container Push
    args: [ 'push', 'asia-docker.pkg.dev/${PROJECT_ID}/asia.gcr.io/emojivoto-voting-svc:${SHORT_SHA}' ]
    waitFor: ['emojivoto-voting-svc Container Build']

  - name: "gcr.io/cloud-builders/gke-deploy"
    id: emojivoto-voting-svc pod GKE deploy
    args:
      - run
      - --filename=deployment/voting.yml
      - --image=asia-docker.pkg.dev/${PROJECT_ID}/asia.gcr.io/emojivoto-voting-svc:${SHORT_SHA}
      - --location=asia-south2-c
      - --cluster=sanjit-gke-demo
      - --output=votingoutput
    waitFor: ['emojivoto-voting-svc Container Push']

  - name: "gcr.io/cloud-builders/gke-deploy"
    id: namespace GKE deploy
    args:
      - run
      - --filename=deployment/ns.yml
      - --location=asia-south2-c
      - --cluster=sanjit-gke-demo
      - --output=nsoutput
    waitFor: ['-']

  - name: "gcr.io/cloud-builders/gke-deploy"
    id: emojivoto-web ingress GKE deploy
    args:
      - run
      - --filename=deployment/ingress.yml
      - --location=asia-south2-c
      - --cluster=sanjit-gke-demo
      - --output=ingressoutput

#  - name: 'gcr.io/cloud-builders/kubectl'
#    id: emojivoto base GKE deploy
#    args: [ 'apply', '-k', 'kustomize/deployment' ]
#    env:
#      - 'CLOUDSDK_COMPUTE_ZONE=asia-south2-c'
#      - 'CLOUDSDK_CONTAINER_CLUSTER=sanjit-gke-demo'
#
#  - name: 'gcr.io/cloud-builders/kubectl'
#    id: emojivoto-web pod GKE deploy
#    args: [
#        'set',
#        'image',
#        'deployment',
#        'web',
#        'web-svc=asia-docker.pkg.dev/${PROJECT_ID}/asia.gcr.io/emojivoto-web:${SHORT_SHA}',
#        '-nemojivoto'
#    ]
#    env:
#      - 'CLOUDSDK_COMPUTE_ZONE=asia-south2-c'
#      - 'CLOUDSDK_CONTAINER_CLUSTER=sanjit-gke-demo'
#    waitFor: ['emojivoto base GKE deploy']
#
#  - name: 'gcr.io/cloud-builders/kubectl'
#    id: emojivoto-emoji-svc pod GKE deploy
#    args: [
#        'set',
#        'image',
#        'deployment',
#        'emoji',
#        'emoji-svc=asia-docker.pkg.dev/${PROJECT_ID}/asia.gcr.io/emojivoto-emoji-svc:${SHORT_SHA}',
#        '-nemojivoto'
#    ]
#    env:
#      - 'CLOUDSDK_COMPUTE_ZONE=asia-south2-c'
#      - 'CLOUDSDK_CONTAINER_CLUSTER=sanjit-gke-demo'
#    waitFor: ['emojivoto base GKE deploy']
#
#  - name: 'gcr.io/cloud-builders/kubectl'
#    id: emojivoto-voting-svc pod GKE deploy
#    args: [
#        'set',
#        'image',
#        'deployment',
#        'voting',
#        'voting-svc=asia-docker.pkg.dev/${PROJECT_ID}/asia.gcr.io/emojivoto-voting-svc:${SHORT_SHA}',
#        '-nemojivoto'
#    ]
#    env:
#      - 'CLOUDSDK_COMPUTE_ZONE=asia-south2-c'
#      - 'CLOUDSDK_CONTAINER_CLUSTER=sanjit-gke-demo'
#    waitFor: ['emojivoto base GKE deploy']
